# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-17 09:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idrettsanlegg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnleggsKategori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AnleggsKlasse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('klasse', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AnleggStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Status', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AnleggsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Fylke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='KartData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngoxkoordinat', models.IntegerField(blank=True, default=0)),
                ('ngoykoordinat', models.IntegerField(blank=True, default=0)),
                ('ngoakse', models.IntegerField(blank=True, default=0)),
                ('utmnord', models.IntegerField(blank=True, default=0)),
                ('utmost', models.IntegerField(blank=True, default=0)),
                ('utmsone', models.IntegerField(blank=True, default=0)),
                ('kpunkt', models.IntegerField(blank=True, default=0)),
                ('Latitude', models.DecimalField(blank=True, decimal_places=13, default=0, max_digits=15)),
                ('Longitude', models.DecimalField(blank=True, decimal_places=13, default=0, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Kommune',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('fylke', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idrettsanlegg.Fylke')),
            ],
        ),
        migrations.RemoveField(
            model_name='idrettsanlegg',
            name='name',
        ),
        migrations.AddField(
            model_name='idrettsanlegg',
            name='Byggeaar',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='idrettsanlegg',
            name='anleggDriver',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='idrettsanlegg',
            name='anleggEier',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='idrettsanlegg',
            name='anleggsnavn',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='idrettsanlegg',
            name='anleggsnummer',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='idrettsanlegg',
            name='areal',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='idrettsanlegg',
            name='bredde',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='idrettsanlegg',
            name='inndratt',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='idrettsanlegg',
            name='lengde',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='idrettsanlegg',
            name='maaldata1',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='idrettsanlegg',
            name='maaldata2',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='idrettsanlegg',
            name='maaldata3',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='idrettsanlegg',
            name='maaldata4',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='idrettsanlegg',
            name='nummer1',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='idrettsanlegg',
            name='ombyggeaar',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='idrettsanlegg',
            name='tildelt',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='idrettsanlegg',
            name='utbetalt',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='idrettsanlegg',
            name='uu',
            field=models.CharField(choices=[('Ja', 'Ja'), ('Nei', 'Nei'), ('Ikke Vurdert', 'Ikke Vurdert')], default='Ikke Vurdert', max_length=20),
        ),
        migrations.AddField(
            model_name='idrettsanlegg',
            name='Anleggskategori',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='idrettsanlegg.AnleggsKategori'),
        ),
        migrations.AddField(
            model_name='idrettsanlegg',
            name='Anleggsklasse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='idrettsanlegg.AnleggsKlasse'),
        ),
        migrations.AddField(
            model_name='idrettsanlegg',
            name='Anleggstype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='idrettsanlegg.AnleggsType'),
        ),
        migrations.AddField(
            model_name='idrettsanlegg',
            name='anleggStatus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='idrettsanlegg.AnleggStatus'),
        ),
        migrations.AddField(
            model_name='idrettsanlegg',
            name='kartdata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='idrettsanlegg.KartData'),
        ),
        migrations.AddField(
            model_name='idrettsanlegg',
            name='kommune',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='idrettsanlegg.Kommune'),
        ),
    ]
