# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-11 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idrettsanlegg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anlegg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anleggsnavn', models.CharField(blank=True, default=0, max_length=20)),
                ('anleggsnummer', models.CharField(blank=True, default=0, max_length=20)),
                ('Status', models.CharField(blank=True, default=0, max_length=20)),
                ('Eier', models.CharField(blank=True, default=0, max_length=20)),
                ('Driver', models.CharField(blank=True, default=0, max_length=20)),
                ('Anleggsklasse', models.CharField(blank=True, default=0, max_length=20)),
                ('Anleggskategori', models.CharField(blank=True, default=0, max_length=20)),
                ('Anleggstype', models.CharField(blank=True, default=0, max_length=20)),
                ('Byggeaar', models.CharField(blank=True, default=0, max_length=20)),
                ('ombyggeaar', models.CharField(blank=True, default=0, max_length=20)),
                ('maaldata1', models.CharField(blank=True, default=0, max_length=20)),
                ('maaldata2', models.CharField(blank=True, default=0, max_length=20)),
                ('maaldata3', models.CharField(blank=True, default=0, max_length=20)),
                ('maaldata4', models.CharField(blank=True, default=0, max_length=20)),
                ('lengde', models.IntegerField(blank=True, default=0)),
                ('bredde', models.IntegerField(blank=True, default=0)),
                ('areal', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AnleggsKlasse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('klasse', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Fylke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='KartData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngoxkoordinat', models.IntegerField(blank=True, default=0)),
                ('ngoykoordinat', models.IntegerField(blank=True, default=0)),
                ('ngoakse', models.IntegerField(blank=True, default=0)),
                ('utmnord', models.IntegerField(blank=True, default=0)),
                ('utmost', models.IntegerField(blank=True, default=0)),
                ('utmsone', models.IntegerField(blank=True, default=0)),
                ('kpunkt', models.IntegerField(blank=True, default=0)),
                ('Latitude', models.DecimalField(blank=True, decimal_places=13, default=0, max_digits=15)),
                ('Longitude', models.DecimalField(blank=True, decimal_places=13, default=0, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Kommune',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('fylke', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idrettsanlegg.Fylke')),
            ],
        ),
        migrations.RemoveField(
            model_name='idrettsanlegg',
            name='name',
        ),
        migrations.AddField(
            model_name='idrettsanlegg',
            name='inndratt',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='idrettsanlegg',
            name='nummer1',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='idrettsanlegg',
            name='tildelt',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='idrettsanlegg',
            name='utbetalt',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='idrettsanlegg',
            name='uu',
            field=models.CharField(blank=True, default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='idrettsanlegg',
            name='anlegg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='idrettsanlegg.Anlegg'),
        ),
        migrations.AddField(
            model_name='idrettsanlegg',
            name='kartdata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='idrettsanlegg.KartData'),
        ),
        migrations.AddField(
            model_name='idrettsanlegg',
            name='kommune',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='idrettsanlegg.Kommune'),
        ),
    ]
