# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-11 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idrettsanlegg', '0002_auto_20160211_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anlegg',
            name='Anleggskategori',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='anlegg',
            name='Anleggsklasse',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='anlegg',
            name='Anleggstype',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='anlegg',
            name='Byggeaar',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='anlegg',
            name='Driver',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='anlegg',
            name='Eier',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='anlegg',
            name='Status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='anlegg',
            name='anleggsnavn',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='anlegg',
            name='anleggsnummer',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='anlegg',
            name='maaldata1',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='anlegg',
            name='maaldata2',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='anlegg',
            name='maaldata3',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='anlegg',
            name='maaldata4',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='anlegg',
            name='ombyggeaar',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
