# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-11 14:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idrettsanlegg', '0003_auto_20160211_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnleggsKategori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AnleggStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Status', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AnleggsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='idrettsanlegg',
            name='uu',
        ),
        migrations.AddField(
            model_name='anlegg',
            name='uu',
            field=models.CharField(choices=[('Ja', 'Ja'), ('Nei', 'Nei'), ('Ikke Vurdert', 'Ikke Vurdert')], default='Ikke Vurdert', max_length=20),
        ),
        migrations.AlterField(
            model_name='anlegg',
            name='Anleggskategori',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='idrettsanlegg.AnleggsKategori'),
        ),
        migrations.AlterField(
            model_name='anlegg',
            name='Anleggsklasse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='idrettsanlegg.AnleggsKlasse'),
        ),
        migrations.AlterField(
            model_name='anlegg',
            name='Anleggstype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='idrettsanlegg.AnleggsType'),
        ),
        migrations.AlterField(
            model_name='anlegg',
            name='Status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='idrettsanlegg.AnleggStatus'),
        ),
    ]
