# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-24 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idrettsanlegg', '0003_auto_20160224_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anleggstatus',
            name='status',
            field=models.CharField(default='Status', max_length=75),
        ),
        migrations.AlterField(
            model_name='idrettsanlegg',
            name='Byggeaar',
            field=models.CharField(blank=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='idrettsanlegg',
            name='anleggDriver',
            field=models.CharField(blank=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='idrettsanlegg',
            name='anleggEier',
            field=models.CharField(blank=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='idrettsanlegg',
            name='anleggsnavn',
            field=models.CharField(blank=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='idrettsanlegg',
            name='anleggsnummer',
            field=models.CharField(blank=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='idrettsanlegg',
            name='maaldata1',
            field=models.CharField(blank=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='idrettsanlegg',
            name='maaldata2',
            field=models.CharField(blank=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='idrettsanlegg',
            name='maaldata3',
            field=models.CharField(blank=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='idrettsanlegg',
            name='maaldata4',
            field=models.CharField(blank=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='idrettsanlegg',
            name='ombyggeaar',
            field=models.CharField(blank=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='idrettsanlegg',
            name='uu',
            field=models.CharField(choices=[('Ja', 'Ja'), ('Nei', 'Nei'), ('Ikke Vurdert', 'Ikke Vurdert')], default='Ikke Vurdert', max_length=75),
        ),
    ]
