# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-24 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idrettsanlegg', '0004_auto_20160224_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idrettsanlegg',
            name='anleggsnavn',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
