# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-11 14:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idrettsanlegg', '0004_auto_20160211_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idrettsanlegg',
            name='anlegg',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='idrettsanlegg.Anlegg'),
        ),
    ]
