# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-09 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idrettsanlegg', '0007_auto_20160302_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idrettsanlegg',
            name='kartdata',
        ),
        migrations.AddField(
            model_name='kartdata',
            name='idrettsanlegg',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='idrettsanlegg.Idrettsanlegg'),
        ),
    ]
